name: My First Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - run: npm ci
    - run: npm test

    - name: Print a message
      run: echo "Hello, world!"
    
    - name: Run custom action
    - run: npm i @actions/core
      uses: nguyenthach4/Create_Custom_Actions/Node.JS_Version@main
      
